### PR TITLE
debian packaging

### PR DESCRIPTION
**Pull request by a-detiste**
I can provide sample systemd 'user' or 'system' .service file if you want for qcma_cli too.

### CODE REVIEW

**Comment by codestation** [comment]
I wil hold on this merge until i test vitamtp->libvitamtp migration.

Also i am not sure about including a systemd unit file. I have to do some testing to see if i should install it on  debian wheezy/jessie and ubuntu precise/trusty/utopic.

**Comment by a-detiste** [comment]
about the systemd service, I was really meaning an example file that lives in /usr/share/doc/qcma/qcma.service.example and is never automatically enabled; most users would use the GUI version.

**Comment by codestation** [comment]
Just to let you know, i added some systemd files in ea9124e99bfc760d5921b253c3df7e05bae2c7ca.
There is a problem where qcma doesn't use the default session address, so it only can receive commands from unit files making the whole dbus support pointless. Not sure how to solve it...

**Comment by a-detiste** [comment]
First, why not just set a `Suggests:` on `dbus-user-session` instead of copying its contents verbatim ?  
It's in experimental, but should land in Debian when Jessie is released. It is still evolving, it might be a hurdle to keep it in sync. https://packages.debian.org/experimental/dbus-user-session

I'll dig how to add support for `--refresh` & `--stop` args to `qcma_cli` instead of asking users to cast
DBus spells ( https://github.com/codestation/qcma/blob/master/qcma_cli.6 ) maybe the various way to connect to dbus could be hidden from the user there.

@smcv

Do you plan to push `dbus-user-session` to Ubuntu ?

**Comment by smcv** [comment]
> First, why not just set a Suggests: on dbus-user-session instead of copying its contents verbatim ?

Please do not copy these units into random projects. The best case is that they will duplicate functionality from dbus and conflict with it, the worst case is breaking a working system. The "user bus" is not a feature for end-user applications to provide; it is a piece of OS plumbing, and enabling it changes the OS's model of what a session means. That's a decision for OS builders, not apps.

If your application is less useful on OSs that don't have the user-session model, well, that's unfortunate, but welcome to the club. I've been working around this in my day job for a while; the initial proposal (not from me) was literally a decade ago, before my involvement in D-Bus.

The entire point of me getting those units landed in dbus upstream was so that people can stop copy-pasting them into vaguely related projects... if you have a problem with D-Bus, the right place to fix it is in D-Bus, not in random downstreams, and that is what I have now done. I'm sorry it took so long, but I submitted the original versions of the relevant patches two years ago and spent most of the intervening time waiting for code review.

> It's in experimental, but should land in Debian when Jessie is released.

Specifically, it will go into unstable when I think it won't cause significant regressions in the rest of the ecosystem (polkit and udisks2 are the projects I've had to patch so far; packagekit also looks suspicious). Arbitrarily enabling this stuff as a side-effect of installing an application is going to break unrelated user services. Please don't do that.

> Do you plan to push dbus-user-session to Ubuntu ?

Not my decision - I don't use or maintain Ubuntu - but Martin Pitt seemed interested in landing it at some future point (I would guess 15.10 or 16.04 - it's too late for 15.04 now).

Now that Ubuntu is moving away from Upstart, and I've finally herded their AppArmor patches for dbus into upstream D-Bus, hopefully they can stop using a fork of the Debian package that I maintain, and start picking up changes from Debian without manual merging.

**Comment by smcv** [comment]
> There is a problem where qcma doesn't use the default session address, so it only can receive commands from unit files making the whole dbus support pointless.

If you wait for the version of dbus that integrates this stuff properly (currently the 1.9.x development branch, which will be released as 1.10 in future) then that problem goes away.

**Comment by a-detiste** [comment]
@codestation 

There is now a real args parser in Qt, but only since Qt 5.2 :-(
http://www.ics.com/blog/whats-new-qt-52-qcommandlineparser

**Comment by a-detiste** [comment]
http://doc.qt.io/qt-4.8/unix-signals.html : so many hoops :cry:

**Comment by codestation** [comment]
@a-detiste i added the dbus unit files because i thought it was required to connect to the default session bus (it wasn't the case). Didn't know that they will gonna be added to debian so I will remove them from the repo.

Adding  --refresh and –stop to qcma_cli doesn't sound bad (I could use QlocalSocket to communicate to the running instance) but that doesn't solve other events where it has to wait for a response like database finilization and received pairing pin (unimplemented for now) events.

Personally I added dbus support so users could control qcma_cli remotely (and an user wanted to build a Gnome3 notifier that communicated with the daemon via dbus).

Didn't know that Qt had a arg parser. Being >= 5.2 is no much problem as Qt 5.3 is on wheezy-backports and jessie, opensuse/fedora have recent versions and I intent to drop Qt4 support soon (thus the users still stuck in Ubuntu 12.04).

@smcv thanks for the input. I am certain that putting qcma_cli in a systemd unit file is the way to go but if dbus support is still lacking in several distros then I will switch to another IPC protocol (like zeromq, so the android port will be easier for me).

**Comment by a-detiste** [comment]
Well, this is getting out of hand, at first I *only* wanted to provide a sample system unit file to avoid that users run qcma_cli as root on their NAS or other headless backup-device.   
I thought that `org.qcma.HeadlessManager.refreshDatabase` could be mapped to `SIGHUP`, with a `ExecReload=/bin/kill -HUP $MAINPID` in the unit file and that would be enough if someone doesn't use D-Bus.  

As I found out here, handling of standard unix signals in Qt feels like a contraption: http://doc.qt.io/qt-4.8/unix-signals.html :cry: 

(org.qcma.HeadlessManager.stop currently doesn't have any added value versus `SIGTERM`)

**Comment by codestation** [comment]
> (org.qcma.HeadlessManager.stop currently doesn't have any added value versus SIGTERM)

It waits until the last pending cma event is completed before exiting. Sometimes the CMA app on the Vita side locked up until a reboot if i closed the usb connection in the middle of a transfer. This was on early development so i never found out if the problem it was my fault or the Vita.

I am moving the dbus/signals discussion to #26 as a pull request for debian packaging isn't  the best place for it.

**Pull request merged**
